export enum ErrorCode {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  BAD_CREDENTIALS = "BAD_CREDENTIALS",
  NOT_FOUND = "NOT_FOUND",
  INPUT_VALIDATION_ERROR = "INPUT_VALIDATION_ERROR",
  EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  TIMEOUT = "TIMEOUT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
}
